"""Add status column to time_entries table

Revision ID: 1a9b842c6d0c
Revises: 
Create Date: 2025-07-20 03:31:47.739822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a9b842c6d0c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_entries', sa.Column('status', sa.String(length=50), nullable=True))
    op.execute("UPDATE time_entries SET status = 'submitted' WHERE status IS NULL")
    op.alter_column('time_entries', 'status', nullable=False)
    op.create_index(op.f('ix_time_entries_status'), 'time_entries', ['status'], unique=False)


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_entries_status'), table_name='time_entries')
    op.drop_column('time_entries', 'status')
    # ### end Alembic commands ###
