"""Add daily hours and mode to time_entries

Revision ID: a48e3c1bc36e
Revises: 1a9b842c6d0c
Create Date: 2025-07-20 23:12:41.825444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a48e3c1bc36e'
down_revision: Union[str, None] = '1a9b842c6d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### START OF EDITED SECTION ###

    # Step 1: Add all new columns, but allow them to be NULL temporarily
    op.add_column('time_entries', sa.Column('daily_mode', sa.Boolean(), nullable=True))
    op.add_column('time_entries', sa.Column('sun', sa.Float(), nullable=True))
    op.add_column('time_entries', sa.Column('mon', sa.Float(), nullable=True))
    op.add_column('time_entries', sa.Column('tue', sa.Float(), nullable=True))
    op.add_column('time_entries', sa.Column('wed', sa.Float(), nullable=True))
    op.add_column('time_entries', sa.Column('thu', sa.Float(), nullable=True))

    # Step 2: Backfill all existing rows with default values
    op.execute("UPDATE time_entries SET daily_mode = FALSE WHERE daily_mode IS NULL")
    op.execute("UPDATE time_entries SET sun = 0.0 WHERE sun IS NULL")
    op.execute("UPDATE time_entries SET mon = 0.0 WHERE mon IS NULL")
    op.execute("UPDATE time_entries SET tue = 0.0 WHERE tue IS NULL")
    op.execute("UPDATE time_entries SET wed = 0.0 WHERE wed IS NULL")
    op.execute("UPDATE time_entries SET thu = 0.0 WHERE thu IS NULL")

    # Step 3: Now that all rows have values, alter the columns to be NOT NULL
    op.alter_column('time_entries', 'daily_mode', nullable=False)
    op.alter_column('time_entries', 'sun', nullable=False)
    op.alter_column('time_entries', 'mon', nullable=False)
    op.alter_column('time_entries', 'tue', nullable=False)
    op.alter_column('time_entries', 'wed', nullable=False)
    op.alter_column('time_entries', 'thu', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_entries', 'thu')
    op.drop_column('time_entries', 'wed')
    op.drop_column('time_entries', 'tue')
    op.drop_column('time_entries', 'mon')
    op.drop_column('time_entries', 'sun')
    op.drop_column('time_entries', 'daily_mode')
    # ### end Alembic commands ###
